version: "2.0"
services:

  scorpius:
    image: jmsfernandes/scorpius:latest
    hostname: scorpius
    container_name: scorpius
    restart: always
    expose:
      - '80'
      - '443'
    ports:
      - "80:80"
      - "443:443"
    environment: # if we dont need/want https support, you can comment all of these lines
      - ASPNETCORE_URLS=https://+;http://+ 
      - Kestrel__Certificates__Default__Path=/app/Certs/cert.pem
      - Kestrel__Certificates__Default__KeyPath=/app/Certs/key.pem
    volumes:
      - ./Scorpius/***REMOVED***.json:/app/firebase_admin.json # map your firebase_admin.json config file 
      #- ./Scorpius/custom-notifications.json:/app/notifications.json #map your notification path to inside of the   
      - ./Scorpius/Certs/cert.pem:/app/Certs/cert.pem #map the certificates and priv key to inside of the container
      - ./Scorpius/Certs/key.pem:/app/Certs/key.pem
    logging:
       options:
         max-size: 50m

